name: format
description: A package for formatting Dart strings like a format method in Python.
version: 1.2.0
homepage: https://github.com/vi-k/format

environment:
  sdk: '>=2.13.4 <3.0.0'

dependencies:
  characters: ^1.2.1
  dart_code_metrics: ^4.17.0
  intl: ^0.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.9
